services:
    databse:
        container_name: "scriba_postgres"
        image: "postgres"
        volumes:
            -   scriba_data:/var/lib/postgresql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: scriba
        ports:
            -   "5432:5432"
volumes:
    scriba_data: